### ISSUE TITLE
Still some references to WooCommerce

### ISSUE THREAD

**Issue by simplycomputing** [ClassicPress-plugins/classicpress-seo#111]
The SEO settings page still has a menu title and 5 references to WooCommerce in the text. Assume this should be changed to Classic Commerce?

![seo-woo](https://user-images.githubusercontent.com/46998578/91702564-44ddff80-ebbc-11ea-9ef2-0c69c011faa5.jpg)

**Comment by simplycomputing** [comment]
Or maybe you want to change it to "Commerce" to make it more generic? It's just that the dashboard toggle mentions Classic Commerce specifically.

**Comment by timbocode** [comment]
Yes, this does need to be changed. I can't imagine many (if any) people will be using CPSEO with Woo so it does make sense to change all occurrences of `WooCommerce` to `Classic Commerce`.

**Comment by simplycomputing** [comment]
I was thinking the same. But then I saw in your revised help section you were mentioning CC and Woo. It probably does make more sense to stick with CC only, as you may find ongoing changes in Woo starts breaking things and you don't want to be going down that rabbit hole.

**Comment by simplycomputing** [comment]
I'd working on a PR for this now. Do you also want to remove references to WooCommerce in the help section? Or maybe add a note to say that it _may_ work with Woo but you won't be guaranteeing it into the future.

**Comment by timbocode** [comment]
The initial intention was to also support Woo **as it stood at the time** but I've no intention of maintaining compatibility with Woo and things have changed considerably since then. I've no idea if it works with WC4+ and I've no plans to test it.

So, yes, we should change all references of WC to CC and also to remove "support for WooCommerce" from the _readme_ too.

**Comment by timbocode** [comment]
Closed by #114
