### ISSUE TITLE
missing module of Buddypress and bbpress

### ISSUE THREAD

**Issue by imunik** [ClassicPress-plugins/classicpress-seo#70]
There is missing module of BuddyPress and bbPress in Dashboard of Classic-seo plugin. due to this there is error in titles and meta, if a (members/member_name/ or groups/group_name/ etc.) pages are visited. It states Page Not Found in the meta and title, even if that profile is available. ( see screenshots > https://res.cloudinary.com/foxm/image/upload/v1587118073/posting%20images%20for%20classicpress.jpg )

Thanks ! Classic-SEO missing a lot more features as compare with Rank Math. but since it is light-weight is appreciated and is in beta.
note: i m using Version 1.0.0-beta.3

**Comment by imunik** [comment]
Here is a screensho of modules of Rank Math for reference -> https://res.cloudinary.com/foxm/image/upload/v1587118612/classicpress-post-img%20-help.jpg

**Comment by timbocode** [comment]
Hi @imunik thanks for getting in touch. Classic SEO does not currently support BuddyPress, bbPress or AMP. A decision was made at the start to omit this functionality from Classic SEO since there seemed little desire amongst the community. Also, as you say, a key aim is to keep Classic SEO as light as possible.

Having said that, if you're experiencing errors using Classic SEO then that is something we need to look at, but I could do with more details please.

1. On the page where you got the "Page Not Found" error, what was the URI? It might have looked something similar to `wp-admin/admin.php?page=` or perhaps `wp-admin/post.php?post=` depending on whether you were on a settings page or a post edit page. Can you let me know everything after `wp-admin` please.

2. Can you give me more details about the nature of the meta errors please?

Thanks.

**Comment by timbocode** [comment]
Closing this issue for the following reasons:

- Can't reproduce the errors
- Errors relate to components that do not exist in Classic SEO
- No similar reports from other users
- No response by author to request for information

Will reopen if further information is provided or uncovered.

**Comment by timbocode** [comment]
Still no response from OP so issue is now closed.
